<?php


    /**
     * Filter used by controllers to ascertain whether
     * the current user has allow on a certain right.
     * We are overriding original class, because we need to avoid
     * printing failure view that is generated by RightsControllerFilter::renderAccessFailureView()
     */
    class ApiRightsControllerFilter extends RightsControllerFilter
    {
        /**
         * Throw exception when user doesn't have rights for requested action.
         * @throws SecurityException
         */
        protected static function renderAccessFailureContent()
        {
            $message = Yii::t('Default', 'You do not have rights to perform this action.');
            throw new SecurityException($message);
        }
    }
?>